sudo: required
language: go
go:
- 1.10.x
install:
- cd electrum && go get . && go build
before_install:
- openssl aes-256-cbc -K $encrypted_1de88eb32b7d_key -iv $encrypted_1de88eb32b7d_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d

addons:
  ssh_known_hosts: 13.229.155.155
after_success:
  - ssh hongjia.hu@13.229.155.155 "touch ~/helloword.txt"